### ISSUE TITLE
Minikube pararmeter " --vm-driver none " support

### ISSUE THREAD

**Issue by karthik101** [andrewrothstein/ansible-minikube#4]
Does the playbook support minikube parameter " --vm-driver none " ? 
If it is then i can do standalone one node installations using this playbook.

Thanks,
Karthik

**Comment by andrewrothstein** [comment]
the role only installs the minikube binary (and the kvm2 driver pkgs+binaries). it doesn't prescribe how to run minikube. if you want to run minikube standalone you likely need a local docker daemon. shameless plug for my [docker role](https://github.com/andrewrothstein/ansible-docker).
